export const DataCatergory = [
  {
    category: 'Shopping',
    desc: 'Buy Some gorceries',
    time: '0/0/0',
    expense: '120',
    income: undefined,
    expenses: undefined,
  },
  {
    category: 'Subscription',
    desc: 'Disney+ Annual',
    time: '0/0/0',
    expense: '80',
    income: undefined,
    expenses: undefined,
  },
  {
    category: 'Food',
    desc: 'Buy a ramen',
    time: '0/0/0',
    expense: '120',
    income: undefined,
    expenses: undefined,
  },
  {
    category: 'Salary',
    desc: 'Salary for July',
    time: '0/0/0',
    expense: undefined,
    income: '5000',
    expenses: undefined,
  },
  {
    category: 'Transportation',
    desc: 'Charging Tesla',
    time: '0/0/0',
    expense: '18',
    income: undefined,
    expenses: undefined,
  },
];
